### ISSUE TITLE
Condition on Autoscale Table is ignored

### ISSUE THREAD

**Issue by samshend** [medikoo/serverless-plugin-dynamodb-autoscaling#1]
Hi! Great plugin, but I have a problem with applying conditions to my settings and couldn't find any docs for this. Could you please help me?

Here's my settings:

```
resources:
  Conditions:
    IsDev:
      Fn::Equals:
        - ${opt:stage}
        - dev
  Resources:
    DynamoDbTable:
      Condition: IsDev
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
custom:
  Conditions:
    IsDev:
      Fn::Equals:
        - ${opt:stage}
        - dev
  capacities:
    - table: DynamoDbTable  # DynamoDB Resource
      Condition: IsDev
      read:
        minimum: 5        # Minimum read capacity
        maximum: 200     # Maximum read capacity
        usage: 0.75       # Targeted usage percentage
      write:
        minimum: 5       # Minimum write capacity
        maximum: 200      # Maximum write capacity
        usage: 0.75        # Targeted usage percentage
plugins:
  - serverless-dynamodb-autoscaling
```

Error I am getting:

```
Serverless Error ---------------------------------------
 
  Template format error: Unresolved resource dependencies [DynamoDbTable] in the Resources block of the template
```
