### ISSUE TITLE
Generated AutoScaling resources assume TableName is same as Table Resource name

### ISSUE THREAD

**Issue by thomasaj** [medikoo/serverless-plugin-dynamodb-autoscaling#10]
The plugin assumes that the name of the Resource in the serverless template and the TableName for that resource are equivalent when generating scalable target and scaling policies for that table.

For a given table resource:
```
TableResource:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: NameOfTable
        AttributeDefinitions:
          - AttributeName: "Id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "Id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
```
The following autoscaling resource is generated:
```
"TableResourceReadScalableTarget": {
      "Type": "AWS::ApplicationAutoScaling::ScalableTarget",
      "Properties": {
        "MaxCapacity": 4000,
        "MinCapacity": 100,
        "ResourceId": {
          "Fn::Join": [
            "/",
            [
              "table",
              {
                "Ref": "TableResource"
              }
            ]
          ]
        },
        "RoleARN": {
          "Fn::ImportValue": "IAM-Role-DynamoDBAutoScalingRole-ARN"
        },
        "ScalableDimension": "dynamodb:table:ReadCapacityUnits",
        "ServiceNamespace": "dynamodb"
      }
```

The plugin should allow the name of the resource and the table name to be different.
