### ISSUE TITLE
Different Min/Max Read/Write Capacities

### ISSUE THREAD

**Issue by RyanCodes** [medikoo/serverless-plugin-dynamodb-autoscaling#6]
@medikoo is it possible to set different read/write Capacities for the tables?

**Comment by RyanCodes** [comment]
figured it out I would add it to the documentation :) 

```
tablesConfig:
  "*":
    read:
      minCapacity: 1
      maxCapacity: 10
      targetUsage: 0.75
    write:
      minCapacity: 1
      maxCapacity: 15
      targetUsage: 0.75
```
