### ISSUE TITLE
Pattern not properly taken into account

### ISSUE THREAD

**Issue by Vadorequest** [medikoo/serverless-plugin-dynamodb-autoscaling#8]
```
  dynamodbAutoscaling:
    tablesConfig:
      "*": false # Disable autoscaling for all dev DBs
      "*production*":
        table:
          minCapacity: 5 # All tables start at 5 WCU/RCU
          maxCapacity: 25 # All table can use up to 25 WCU/RCU if needed, should only be useful for simulation/save due to its huge amount of data saved
          targetUsage: 0.3 # Trigger autoscaling early because it needs at least 5mn before to actually scale up
```

If I use this setup, my production table don't get any autoscaling, it gets deactivated.

If I remove `"*": false`, then my staging table get the default values (200 RCU/WCU) and my production table get the proper values

My table names are like:

student-loan-simulator-server-production-simulations
student-loan-simulator-server-staging-simulations

I don't understand why it doesn't work, it should.

**Comment by medikoo** [comment]
> My table names are like:

Which version are you using? Since v3 it's resource names (not table names) that should be referenced in `tablesConfig`

**Comment by Vadorequest** [comment]
Well, I installed the package yesterday so I'd assume I was on the latest version.

`"serverless-plugin-dynamodb-autoscaling": "3.0.0",`

I think I used `table` because it's stated in the doc: 
![image](https://user-images.githubusercontent.com/3807458/47786455-21ba3e80-dd0c-11e8-9cb8-1398ff176d6c.png)

But I tried without it with the same behaviour.

**Comment by medikoo** [comment]
In this case `table` means that you want tweak settings of a _table_ in general (it's not table name) and not _indexes_ (see separate settings for _indexes_ are indicated under _indexes_ below)

The `Table4` is reference to table resource name.

So ensure you address you're table resource names right, and if it still doesn't work for you. Let me know the exact settings and resource names for which it doesn't work

**Comment by Vadorequest** [comment]
Yes, exactly, I don't know what it does to indexes so I prefer not to enable autoscaling for those, without really knowing what it does underneath.

Here is my `sls print`:

```yaml
frameworkVersion: =1.30.3
plugins:
  - serverless-plugin-dynamodb-autoscaling
custom:
  dynamodbAutoscaling:
    tablesConfig:
      '*': false
      '*production*':
        table:
          minCapacity: 5
          maxCapacity: 25
          targetUsage: 0.3

resources:
  Resources:
    simulationsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: student-loan-simulator-server-production-simulations
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
    leadsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: student-loan-simulator-server-production-leads
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
    feedbacksTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: student-loan-simulator-server-production-feedbacks
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

```

I removed all the noise from this output and only kept relevant information

**Comment by medikoo** [comment]
So in given case it' can't match.

Note that you use `*production*` pattern, to match table resource names as : `simulationsTable`, `leadsTable` and `feedbacksTable`.

I'm closing this, but in case of further doubts do not hesitate to ask

**Comment by Vadorequest** [comment]
Ahhh, I get it! I thought it was matched against the `TableName`, not the resource name! Thanks for helping me out. :)

**Comment by Vadorequest** [comment]
@medikoo How would you disable autoscaling based on the environment? I don't find a proper way of doing so.

I thought about using 

```yml
Fn::Equals:
        - ${self:custom.env}
        - "production"
```

But don't really find how to use it

**Comment by medikoo** [comment]
> I thought it was matched against the TableName, not the resource name

I've improved the doc, so this stands out more. Hopefully there'll be no more confusion

> @medikoo How would you disable autoscaling based on the environment? 

Good question. Plugin relies on CloudFormation template that has already all Serverless variables resolved, but none of CF functions are resolved, and as I'm not aware of utility that could help with that, then basing on such resolution seems not feasible.

That means the only resort is to rely on SLS variables, where e.g. in this case you could probably create tables configuration in external files for reach stage individually and import expected config, as e.g.:

```yaml
custom:
  dynamodbAutoscaling:
    tablesConfig:  ${file(dynamodb-config.${opt:stage}.yaml)}
```

(but I haven't tested such approach)
